version: '3' # specify docker-compose version

services:
  vite: # name of the first service
    build: ./frontend/ # specify the directory of the Dockerfile
    ports:
      - "9081:8080" # maps port 4200 on localhost to 80 in container
    depends_on:
      - "express"
    links:
      - express

  express: # name of the second service
    build: ./backend/ # specify the directory of the Dockerfile
    ports:
      - "9080:5000" # maps port 8000 on localhost to 8000 in container
  
  nginx:
    build: ./nginx
    ports:
      - "80:80"